{% set name = "tantivy" %}
{% set version = "0.22.2" %}

package:
  name: {{ name|lower }}-py
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tantivy-{{ version }}.tar.gz
  sha256: b3d0f19271365ccf6e69f0318ea0c3c3438515fee453618977787d6b41da833a

build:
  noarch: python
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  missing_dso_whitelist:
    - "*lib/libgcc_s.so.1"  # [linux]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }} <1.80
    - cargo-bundle-licenses

  host:
    - python {{ python_min }}
    - maturin <=1.3.2
    - pip

  run:
    - python >={{ python_min }}

test:
  imports:
    - tantivy
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/quickwit-oss/tantivy
  summary: Fast full-text search engine library written in Rust
  license: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE

extra:
  recipe-maintainers:
    - mediocretech
