# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.26.0"

package:
  name: tantivy-py
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/tantivy/tantivy-${{ version }}.tar.gz
  sha256: 7c9507fcc62bac4ef1d40b1ed37ff7fa07e44b5043b30288f63bcf4fdc62644a

build:
  number: 0
  script:
    env:
      CARGO_TARGET_POWERPC64LE_UNKNOWN_LINUX_GNU_LINKER: $CC
    content:
      - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
    - cmake
    - make
  host:
    - maturin >=1.0,<2.0
    - pip
    - python
  run:
    - python

tests:
  - python:
      imports: tantivy
  - requirements:
      run:
        - pytest-cov
        - mktestdocs
    files:
      source:
        - tests/
    script:
      - coverage run --source=tantivy --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=100

about:
  summary: Fast full-text search engine library written in Rust
  license: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE
  homepage: https://pypi.org/project/tantivy
  repository: https://github.com/quickwit-oss/tantivy-py
  documentation: https://tantivy-py.readthedocs.io

extra:
  recipe-maintainers:
    - mediocretech
    - bollwyvl
